### ISSUE TITLE
application not working on python3

### ISSUE THREAD

**Issue by harshadyeola** [sehgalvibhor/Blog-CLI#1]
Please make sure that your application/script works with python3.
With python3 i get following error. 

```
me@localhost:/vagrant/Blog-CLI$ python3 blog.py --help
Traceback (most recent call last):
  File "blog.py", line 147, in <module>
    main()
  File "blog.py", line 138, in main
    with MyApp() as app:
AttributeError: __exit__\
```

**Comment by sehgalvibhor** [comment]
Hi,

Can you please specify the python3 version you are working, so that i can
emulate similar conditions.?

Thanks.

**Comment by harshadyeola** [comment]
@sehgalvibhor 

can you make your application or script compatible with python 3.x versions?

Btw we need your application to work with latest version of python.

**Comment by sehgalvibhor** [comment]
Actually I did try it on python3 by creating a virtual environment,  it was
running properly.  Let me debug it and update you on this.

Thanks.

**Comment by sehgalvibhor** [comment]
@harshadyeola 

Strange, I tried it out on both windows and linux, using Python 3.4.2 on both. It works perfectly.
However, I have fixed the issue , 'with' clause require an **exit** attribute.

Please try running it now !

**Comment by sehgalvibhor** [comment]
@harshadyeola 

Is it working now? Shall i close the issue?
