### ISSUE TITLE
No proper error handling

### ISSUE THREAD

**Issue by harshadyeola** [sehgalvibhor/Blog-CLI#2]
## No error handling for category add with blank argument

```
user@example.com:~/Blog-CLI$ python3 blog.py Category add
INFO: Category Added
user@example.com:~/Blog-CLI$ 
```
## No error handling for post add with same ID

```
user@example.com:~/Blog-CLI$ python3 blog.py Post add --id 1 --title First --content "This is my first blog"
INFO: Blog Added
user@example.com:~/Blog-CLI$ python3 blog.py Post add --id 1 --title First --content "This is my first blog update"
INFO: Blog Added
vagrant@precise32:/vagrant/Blog-CLI$ 
```

**Comment by sehgalvibhor** [comment]
Okay!
I'll add proper error handling.

**Comment by sehgalvibhor** [comment]
@harshadyeola 

Error handling for the blog has been added.
Try running it now !
Thanks!

**Comment by sehgalvibhor** [comment]
@harshadyeola 

Error handling for the blog has been added.
Try running it now !
Thanks!

**Comment by sehgalvibhor** [comment]
@harshadyeola 

Please close this issue if it's working now.

**Comment by sehgalvibhor** [comment]
@harshadyeola 

It's done ! marking it as closed.
