### ISSUE TITLE
Install Dependencies required by  application

### ISSUE THREAD

**Issue by harshadyeola** [sehgalvibhor/Blog-CLI#3]
Can you install dependencies required by your application while using your application? 

something like setuptools etc.

```
user@example.com:~/Blog-CLI# python3 blog.py --help
Traceback (most recent call last):
  File "blog.py", line 1, in <module>
    from cement.core.foundation import CementApp
ImportError: No module named 'cement'
```

**Comment by sehgalvibhor** [comment]
Okay !
Let me give it a shot ! I'll try doing that.

**Comment by sehgalvibhor** [comment]
@harshadyeola 

This issue has been fixed ! The script now installs cement as soon as you run it the first time.
Please check it and mark it as closed.

Thanks.

**Comment by sehgalvibhor** [comment]
@harshadyeola 

But you will definitely need pip for this.

**Comment by sehgalvibhor** [comment]
@harshadyeola 
Try it now !
But you will definitely need pip for this , can't think anything without pip.

**Comment by sehgalvibhor** [comment]
@harshadyeola 

It's done ! Marking it as Closed.
