### ISSUE TITLE
post update issue on database

### ISSUE THREAD

**Issue by iam404** [sehgalvibhor/Blog-CLI#4]
> vagrant@precise32:~/Blog-CLI$ python3 blog.py Post add --id 1 --title First --content "This is my first blog"
> Installing module
> Collecting cement
> Downloading cement-2.6.2.tar.gz (140kB)
>  100% |################################| 143kB 434kB/s 
> Installing collected packages: cement
> Running setup.py install for cement
> Successfully installed cement
> Re-run the application

hii
make sure while i run 
`python3 blog.py Post add --id 1 --title First --content "This is my first blog"`
apart from installing cement , it should also update my post on database

**Comment by sehgalvibhor** [comment]
Hi,

Sure!
Let me give it a try.

Thanks.

**Comment by sehgalvibhor** [comment]
@iam404 

Hey,
I have updated the code.
Now you can access/make changes to the database ,while installing cement simultaneously. 
Please mark it closed, after testing it.
Thanks.

**Comment by sehgalvibhor** [comment]
@iam404 

Hey,
I have updated the code.
Now you can access/make changes to the database ,while installing cement simultaneously. 
Please mark it closed, after testing it.
Thanks.

**Comment by sehgalvibhor** [comment]
Closing this !
